widgets:
  - name: image
    description: An image widget
    icon: image
    html: image/view.html
    css: image/style.css
    editor:
      - type: image
        label: Image from Assets
        name: src
        placeholder: Image URL
      - type: text
        label: Direct Image URL
        name: url
        placeholder: HTTP image URL
      - type: text
        label: Alt
        name: alt
        placeholder: Enter alt text
      - type: text
        label: Caption
        name: caption
        placeholder: Enter caption
      - type: select
        label: Fit
        name: fit
        options:
          - label: Cover
            value: cover
          - label: Contain
            value: contain
          - label: None
            value: none
          - label: Fill
            value: fill
          - label: Scale Down
            value: scale-down
        default: cover
  - name: header
    description: A header widget
    icon: header
    html: header/view.html
    editor:
      - type: select
        label: Size
        name: size
        options:
          - label: Large
            value: large
          - label: Medium
            value: medium
          - label: Small
            value: small
        default: medium
      - type: text
        label: Text
        name: text
        placeholder: Enter text
  - name: markdown
    description: A markdown widget
    icon: markdown
    html: markdown/view.html
    css: markdown/style.css
    editor:
      - type: textarea
        label: Markdown
        name: text
        placeholder: Enter markdown text
        required: true
  - name: section
    description: Section
    icon: borderNone
    html: section/view.html
    css: section/style.css
    editor:
      - type: select-buttons
        label: Direction
        name: direction
        options:
          - label: Responsive
            value: responsive
            icon: columns
          - label: Column
            value: column
            icon: down
          - label: Row
            value: row
            icon: right
        default: column
      - type: select-buttons
        label: Vertical Alignment
        name: alignment_vertical
        options:
          - label: top
            value: top
            icon: top
          - label: center
            value: center
            icon: middle
          - label: bottom
            value: bottom
            icon: bottom
        default: top
      - type: select-buttons
        label: Horizontal Alignment
        name: alignment_horizontal
        options:
          - label: left
            value: left
            icon: left
          - label: center
            value: center
            icon: center
          - label: right
            value: right
            icon: right
        default: left
      - type: boolean
        label: Wrap
        name: wrap
        default: false
      - type: select
        label: Gap
        name: gap
        options:
          - label: 0
            value: 0
          - label: 4
            value: 4
          - label: 8
            value: 8
          - label: 12
            value: 12
          - label: 16
            value: 16
          - label: 20
            value: 20
        default: 0
  - name: form
    description: A Form
    icon: columns
    html: form/form.html
    css: form/style.css
    editor:
      - type: text
        label: URL
        name: url
        description: URL to POST data to
      - type: select
        label: Method
        name: method
        options:
          - label: GET
            value: GET
            icon: get
          - label: POST
            value: POST
            icon: post
        default: POST
      - type: select
        label: Encoding
        name: encoding
        options:
          - label: URL
            value: url
            icon: url
          - label: Form
            value: form
            icon: form
        default: form

  - name: form_input
    description: A Form Input
    icon: squareCheck
    html: form/input.html
    editor:
      - type: text
        label: Label
        name: label
        description: Label of the input
      - type: text
        label: Name
        name: name
        description: Internal name of the input
      - type: select
        label: Type
        name: type
        options:
          - label: Text
            value: text
            icon: text
          - label: Email
            value: email
            icon: email
          - label: Hidden
            value: hidden
            icon: hidden
          - label: Password
            value: password
            icon: password
        default: text
      - type: text
        name: default_value
        label: Default Value
        description: Default value of the input
  - name: link
    description: A Link
    icon: link
    html: link/view.html
    editor:
      - type: text
        label: Text
        name: text
        placeholder: Enter text, or add children to this widget
      - type: text
        label: URL
        name: url
        placeholder: Enter URL
      - type: text
        label: Target
        name: target
        placeholder: Enter target
