server:
  port: 8006
  host: 0.0.0.0
  reload: true
  etag_salt: "%Y-%m-%d" # change this to a random string to invalidate the etag. Set to a date format to invalidate the etag on every change
  allow_origins: # CORS
    - http://localhost:1234
    - http://localhost:3000
    - http://localhost:8005
    - http://127.0.0.1:1234
    - http://127.0.0.1:3000
    - http://127.0.0.1:8005

  render: true

debug: false

# tags from stores are inherited into their elements, for exmaple
# jinja2 at store, makes all the elements jinja2 rendered.
stores:
  - name: default
    type: db
    url: sqlite://./data/pe.db
    tags:
      - writable
      - pages
      - templates
  - name: pages
    type: file
    path: ./builtin/pages/
    tags:
      - pages
      - templates
  - name: builtin
    type: file
    path: ./builtin/widgets/
    tags:
      - widgets
      - jinja2
  # allow HTTP based stores
  # - name: http
  #   type: http
  #   base_urls: # only allow HTTP request that start like any of these. Leave empty for all.
  #     - http://localhost:8000/api/v1/element/
# test comment
