server:
  port: 8000
  host: 0.0.0.0
  reload: true
  directory:
    - docs
  etag_salt: "%Y-%m-%d" # change this to a random string to invalidate the etag. Set to a date format to invalidate the etag on every change

page_path: ./docs
templates:
  paths:
    - ./templates/

debug: true

elements:
  - name: text
    type: builtin
    templating: jinja2 # this is the default, but it can be overridden for each element
    viewer: text/view.html
    css: text/style.css
    editor:
      type: form
      fields:
        - id: text
          type: rich-text

  - name: image
    type: builtin
    viewer: image/view.html
    css: image/style.css
    editor:
      - id: image
        type: image
        accept: image/*
        maxSize: 10240000
        minSize: 1024
  - name: header
    type: builtin
    viewer: header/view.html
    css: header/style.css
    editor: header/editor.html
  - name: section
    type: builtin
    viewer: section/view.html
    css: section/style.css
    editor: section/editor.html
  - name: tag-cloud
    type: builtin
    viewer: tag-cloud/view.html
    css: tag-cloud/style.css
    editor: tag-cloud/editor.html
  - name: paragraph
    type: builtin
    viewer: text/view.html
    css: text/style.css
    editor: text/editor.html
  - name: menu
    type: builtin
    viewer: menu/view.html
    css: menu/style.css
    editor: menu/editor.html
  - name: markdown
    type: builtin
    viewer: markdown/view.html
    css: markdown/style.css
    editor: markdown/editor.html
  - name: children
    type: builtin
    viewer: children/view.html
    css: children/style.css
    editor: children/editor.html

  # Examples,
  - name: text-api
    type: http
    templating: none # no templating is used, just the raw HTML and CSS. But could be jinja2. Be sure you trust the source!
    description: |
      Uses the API to render the text element. Noemally just use the builtin, but this proves
      how to use the API to get an element from another server and render it.
    method: GET
    viewer: http://localhost:8000/api/v1/element/text/html
    css: http://localhost:8000/api/v1/element/text/css
