server:
  port: 8000
  host: 0.0.0.0
  reload: true
  directory:
    - docs
  etag_salt: "%Y-%m-%d" # change this to a random string to invalidate the etag. Set to a date format to invalidate the etag on every change

page_path: ./docs
debug: true

# tags from stores are inherited into their elements, for exmaple
# jinja2 at store, makes all the elements jinja2 rendered.
stores:
  - name: docs
    type: file
    path: ./docs/
    tags:
      - pages
      - templates
  - name: builtin
    type: file
    path: ./builtin/
    tags:
      - blocks
      - jinja2
  - name: http
    type: http
    # This is the base URL for the HTTP store. It is used to load the elements.
    # if not set should use full url, but its less secure
    base_url: http://localhost:8000/api/v1/element/
    tags:
      - pages
      - templates
  - name: db
    type: db
    url: sqlite://./data/pe.db

elements:
  - name: text
    store: builtin
    html: text/view.html
    css: text/style.css
  - name: image
    store: builtin
    html: image/view.html
    css: image/style.css
  - name: header
    store: builtin
    html: header/view.html
    css: header/style.css
  - name: section
    store: builtin
    html: section/view.html
    css: section/style.css
  - name: tag-cloud
    store: builtin
    html: tag-cloud/view.html
    css: tag-cloud/style.css
  - name: paragraph
    store: builtin
    html: text/view.html
    css: text/style.css
  - name: menu
    store: builtin
    html: menu/view.html
    css: menu/style.css
  - name: markdown
    store: builtin
    html: markdown/view.html
    css: markdown/style.css
  - name: children
    store: builtin
    html: children/view.html
    css: children/style.css

  # Examples,
  - name: text-api
    description: |
      Uses the API to render the text element. Normally just use the builtin, but this proves
      how to use the API to get an element from another server and render it.
    store: http
    method: GET
    html: text/html
    css: text/css
    tags:
      - data_at_query
