blocks:
  - name: text
    description: A text element
    icon: text
    html: text/view.html
    css: text/style.css
    editor:
      - type: textarea
        label: Text
        name: text
        placeholder: Enter text
  - name: image
    description: An image element
    icon: image
    html: image/view.html
    css: image/style.css
    editor:
      - type: image
        label: Image
        name: src
        placeholder: Image URL
      - type: text
        label: Alt
        name: alt
        placeholder: Enter alt text
      - type: text
        label: Caption
        name: caption
        placeholder: Enter caption
  - name: header
    description: A header element
    icon: header
    html: header/view.html
    css: header/style.css
    editor:
      - type: text
        label: Text
        name: text
        placeholder: Enter text
  - name: section
    description: A section element
    icon: section
    html: section/view.html
    css: section/style.css
    editor:
      - type: textarea
        label: Text
        name: text
        placeholder: Enter text
  - name: tag-cloud
    description: A tag cloud element
    icon: tag
    html: tag-cloud/view.html
    css: tag-cloud/style.css
    editor:
      - type: text
        label: Title
        name: tags
        placeholder: Enter tags
  - name: paragraph
    description: A paragraph element
    icon: paragraph
    html: text/view.html
    css: text/style.css
    editor:
      - type: textarea
        label: Text
        name: text
        placeholder: Enter text
  - name: menu
    description: A menu element
    icon: menu
    html: menu/view.html
    css: menu/style.css
  - name: markdown
    description: A markdown element
    icon: markdown
    html: markdown/view.html
    css: markdown/style.css
    editor:
      - type: text
        label: Title
        name: title
        placeholder: Enter title
        required: true
      - type: textarea
        label: Markdown
        name: text
        placeholder: Enter markdown text
        required: true
  - name: children
    description: A children element
    icon: children
    html: children/view.html
    css: children/style.css
  - name: button
    description: A button element
    icon: button
    html: button/view.html
    css: button/style.css
    editor:
      - type: text
        label: Text
        name: text
        placeholder: Enter text
      - type: textarea
        label: Onclick
        name: onclick
        placeholder: Enter onclick javascript
  - name: div
    description: A div element
    icon: div
    html: div/view.html
    css: div/style.css
  - name: html
    description: A HTML element
    icon: html
    html: html/view.html
    editor:
      - type: html
        label: HTML
